AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: true
          RestrictPublicBuckets: true
Outputs:
  BucketName:
    Description: "The name of the S3 bucket for storing Lambda function code"
    Value: !Ref DeploymentBucket
