Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket where the Lambda function code is stored
    Default: my-bucket

Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !Ref MyFunction

  MyFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: index.handler
      Role: !GetAtt MyRole.Arn
      Runtime: nodejs14.x
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: code.zip
      Environment:
        Variables:
          PARAM1: value
      Timeout: 30

  MyRole:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-bucket/my-role-stack.yaml
      Parameters:
        MyBucket:
          Ref: MyBucket
