name: Deploy Lambda Function
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Build Lambda Function
      run: |
        npm i
        npm run build
        zip -r my-lambda-function.zip dist

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --stack-name my-lambda-stack \
          --template-file infra/template.yaml \
          --parameter-overrides MyBucket=my-bucket MyLambdaDeployBucket=my-lambda-deploy-bucket \
          --capabilities CAPABILITY_IAM
